css-brochure-form - Monique Chang
moniquechang/c0622-code-solutions pull request #15
Opened 2022-06-30 15:55 UTC by moniquechang

<img width="1440" alt="css-brochure-form" src="https://user-images.githubusercontent.com/103399595/176723204-0be494da-7df2-4976-af6c-c1e5a1a568d5.png">

2022-06-30 17:22 UTC, codingcodymiller requested changes
Hey Monique, your form is too wide as compared to the example, please revise and submit a new screenshot with your revision.

2022-07-01 07:20 UTC, moniquechang commented
<img width="1440" alt="css-brochure-form edited" src="https://user-images.githubusercontent.com/103399595/176844746-c6e9afd8-12af-438c-8ba0-cef4e22615c5.png">

here is the edited form!

2022-07-01 17:34 UTC, codingcodymiller requested changes

2022-07-01 17:34 UTC, codingcodymiller commented on css-brochure-form/index.html
> +  </div>
This should be inside the `form` element, it is a part of the `form`

2022-07-01 21:58 UTC, codingcodymiller approved these changes

2022-07-03 00:16 UTC, merged